### ISSUE TITLE
Docker-SoftetherVPN:latest

### ISSUE THREAD

**Issue by JanJans640** [SoftEtherVPN/SoftetherVPN-docker#3]
Hi everyone,

First of all thanks for all the work done to build such a great software.
Now I would like to ask an question.
Is it possible to make an arm64 docker image for the latest branch (5-series)?
Currently I use the stable one on my Raspberry Pi 4 and it works great.
I like to try the latest one with the wireguard addition.
Thanks.
Jan

**Comment by weidi** [comment]
Hi Jan, 
right now there is still an issue #1  where cross compiling the image is not working. I build an arm64 version for you manually so feel free to try `softethervpn/vpnserver:arm64`
I will try to bring up a selfhostet runner to build it automatically.

**Comment by weidi** [comment]
Just created a CI that pushes to softethervpn/vpnserver-arm64 
Feel free to try.
