### ISSUE TITLE
The architecture of vpnserver_arm64 isn't correct.

### ISSUE THREAD

**Issue by Raspberry-Monster** [SoftEtherVPN/SoftetherVPN-docker#7]
https://hub.docker.com/r/softethervpn/vpnserver-arm64/tags
The arch of docker image is amd64 instead of aarch 64. So the software cannot run.
If the image is uploaded by the SoftEther team, please replace the image to the correct architecture. If not, please let me know so that I can use another image or use standalone version instead. Thank you.

**Comment by weidi** [comment]
Thank you for the hint, had an issue in the CI Pipeline config. 
Fixed now

**Comment by Raspberry-Monster** [comment]
Okay. Thanks.
